local Color, colors, Group, groups, styles = require('colorbuddy').setup()

Color.new('background',	'#21272e')
Color.new('black',     	'#21272e')
Color.new('darkgray',  	'#495162')
Color.new('gray',				'#5e646b')
Color.new('maroon',    	'#a82215')
Color.new('darkred',   	'#a82215')
Color.new('red',       	'#e74c3c')
Color.new('green',     	'#218b46')
Color.new('lime',      	'#30c965')
Color.new('olive',     	'#9cd230')
Color.new('yellow',    	'#ede61f')
Color.new('navy',      	'#124792')
Color.new('blue',      	'#2675e4')
Color.new('purple',    	'#a81552')
Color.new('fuchsia',   	'#e42675')
Color.new('teal',      	'#1abc9c')
Color.new('cyan',      	'#1abc9c')
Color.new('aqua',      	'#56b5c2')
Color.new('silver',    	'#9da5b4')
Color.new('lightgray', 	'#9da5b4')
Color.new('white',     	'#f8f8f0')

-- Nvim Groups
Group.new('CursorColumn', groups.CursorLine, groups.CursorLine, groups.CursorLine)
Group.new('CursorLine', nil, colors.darkgray, nil)
Group.new('DiagnosticError', groups.Error, groups.Error, groups.Error)
Group.new('DiagnosticInfo', groups.Info, groups.Info, groups.Info)
Group.new('DiagnosticWarn', groups.Warn, groups.Warn, groups.Warn)
Group.new('DiffAdd', colors.green, nil, nil)
Group.new('DiffChange', colors.silver, nil, nil)
Group.new('DiffDelete', colors.maroon, nil, nil)
Group.new('Directory', colors.olive, nil, nil)
Group.new('Error', colors.white, colors.red, styles.bold)
Group.new('ErrorMsg', groups.Error, groups.Error, groups.Error)
Group.new('Info', colors.silver, colors.background, nil)
Group.new('LineNr', colors.yellow, nil, nil)
Group.new('LineNrAbove', colors.silver, nil, nil)
Group.new('LineNrBelow', groups.LineNrAbove, nil, nil)
Group.new('NvimInternalError', groups.Error, groups.Error, groups.Error)
Group.new('PMenuSel', colors.black, colors.lime, nil)
Group.new('Search', nil, colors.green, nil)
Group.new('StatusLine', nil, colors.red, nil)
Group.new('StatusLineNC', nil, colors.black, nil)
Group.new('VertSplit', colors.white, nil, nil)
Group.new('Warn', colors.black, colors.yellow, styles.bold)
Group.new('WildMenu', groups.Search, groups.Search, groups.Search)

-- Treesitter syntax stuff
Group.new('TSComment', colors.silver, nil, nil)
Group.new('TSConstBuiltin', colors.aqua, nil, nil)
Group.new('TSConstMacro', colors.blue, nil, nil)
Group.new('TSConstant', colors.aqua, nil, nil)
Group.new('TSConstructor', colors.teal, nil, nil)
Group.new('TSDanger', colors.black, colors.red, nil)
Group.new('TSField', colors.white, nil, nil)
Group.new('TSFuncMacro', colors.yellow, nil, nil)
Group.new('TSFunction', colors.red, nil, nil)
Group.new('TSInclude', colors.maroon, nil, nil)
Group.new('TSInclude', colors.teal, nil, nil)
Group.new('TSKeyword', colors.teal, nil, nil)
Group.new('TSLabel', colors.fuchsia, nil, nil)
Group.new('TSNamespace', colors.white, nil, nil)
Group.new('TSNote', colors.black, colors.white, nil)
Group.new('TSOperator', colors.red, nil, nil)
Group.new('TSProperty', colors.white, nil, nil)
Group.new('TSPunctBracket', colors.white, nil, nil)
Group.new('TSPunctDelimiter', colors.red, nil, nil)
Group.new('TSPunctSpecial', colors.red, nil, nil)
Group.new('TSString', colors.lime, nil, nil)
Group.new('TSType', colors.maroon, nil, nil)
Group.new('TSTypeBuiltin', colors.maroon, nil, nil)
Group.new('TSVariable', colors.white, nil, nil)
Group.new('TSWarning', colors.black, colors.yellow, nil)

-- TODO:
-- Language Specific Syntax

-- Default Fallback Syntax
Group.new('Boolean', colors.aqua, nil, nil)
Group.new('Character', colors.lime, nil, nil)
Group.new('Comment', colors.silver, nil, nil)
Group.new('Constant', colors.aqua, nil, nil)
Group.new('Function', colors.red, nil, nil)
Group.new('Identifier', colors.white, nil, nil)
Group.new('Keyword', colors.teal, nil, nil)
Group.new('Number', colors.aqua, nil, nil)
Group.new('PreProc', colors.yellow, nil, nil)
Group.new('Special', colors.red, nil, nil)
Group.new('StorageClass', colors.red, nil, nil)
Group.new('String', colors.lime, nil, nil)
Group.new('Title', colors.red, nil, nil)
Group.new('Type', colors.maroon, nil, nil)
