local Color, colors, Group, groups, styles = require('colorbuddy').setup()

Color.new('background',	'#21272e')
Color.new('black',     	'#21272e')
Color.new('darkgray',  	'#495162')
Color.new('gray',				'#5e646b')
Color.new('maroon',    	'#a82215')
Color.new('darkred',   	'#a82215')
Color.new('red',       	'#e74c3c')
Color.new('green',     	'#218b46')
Color.new('lime',      	'#30c965')
Color.new('olive',     	'#9cd230')
Color.new('yellow',    	'#ede61f')
Color.new('navy',      	'#124792')
Color.new('blue',      	'#2675e4')
Color.new('purple',    	'#a81552')
Color.new('fuchsia',   	'#e42675')
Color.new('teal',      	'#1abc9c')
Color.new('cyan',      	'#1abc9c')
Color.new('aqua',      	'#56b5c2')
Color.new('silver',    	'#9da5b4')
Color.new('lightgray', 	'#9da5b4')
Color.new('white',     	'#f8f8f0')

Group.new('Error', colors.white, colors.red, styles.bold)
Group.new('DiagnosticError', groups.Error, groups.Error, groups.Error)
Group.new('ErrorMsg', groups.Error, groups.Error, groups.Error)
Group.new('Warn', colors.black, colors.yellow, styles.bold)
Group.new('DiagnosticWarn', groups.Warn, groups.Warn, groups.Warn)
Group.new('Info', colors.silver, colors.background, nil)
Group.new('DiagnosticInfo', groups.Info, groups.Info, groups.Info)
Group.new('String', colors.lime, nil, nil)
Group.new('Character', colors.lime, nil, nil)
Group.new('Constant', colors.aqua, nil, nil)
Group.new('Number', colors.aqua, nil, nil)
Group.new('Boolean', colors.aqua, nil, nil)
Group.new('Float', colors.aqua, nil, nil)
Group.new('Function', colors.red, nil, nil)
Group.new('Identifier', colors.aqua, nil, nil)
Group.new('Conditional', colors.red, nil, nil)
Group.new('Repeat', colors.red, nil, nil)
Group.new('Operator', colors.maroon, nil, nil)
Group.new('Keyword', colors.teal, nil, nil)
Group.new('Special', colors.teal, nil, nil)
Group.new('Type', colors.teal, nil, nil)
Group.new('Structure', colors.teal, nil, nil)
Group.new('Include', colors.navy, nil, nil)
Group.new('Define', colors.navy, nil, nil)
Group.new('Comment', colors.gray, nil, nil)
Group.new('NonText', groups.Comment, groups.Comment, groups.Comment)
Group.new('NvimInternalError', groups.Error, groups.Error, groups.Error)
Group.new('CursorLine', nil, colors.darkgray, nil)
Group.new('CursorColumn', groups.CursorLine, groups.CursorLine, groups.CursorLine)
Group.new('Directory', colors.olive, nil, nil)
Group.new('StatusLine', nil, colors.red, nil)
Group.new('StatusLineNC', nil, colors.black, nil)
Group.new('LineNr', colors.yellow, nil, nil)
Group.new('LineNrAbove', colors.silver, nil, nil)
Group.new('LineNrBelow', groups.LineNrAbove, nil, nil)
Group.new('VertSplit', colors.white, nil, nil)
Group.new('Search', nil, colors.green, nil)
Group.new('WildMenu', groups.Search, groups.Search, groups.Search)
Group.new('DiffAdd', colors.green, nil, nil)
Group.new('DiffDelete', colors.maroon, nil, nil)
Group.new('DiffChange', colors.silver, nil, nil)
Group.new('PMenuSel', colors.black, colors.lime, nil)
